### ISSUE TITLE
Scripts to create schema?

### ISSUE THREAD

**Issue by rywem** [NTDLS/TightWiki#1]
Hi there,

Do you have a script to create schema for initial setup? I am not able to locate this

**Comment by NTDLS** [comment]
> Nevermind, I figured it out, Had to use the scripts in the root directory.

I’m so annoyed that I’m not getting notifications on these issues. PLEASE feel free to email me, my email address is on my GitHub profile.

Also, this wiki is still being actively developed and I’d love any feedback - if you want an account on TightWiki.com to tinker, I’d be happy to set one up.

Thanks for checking it out!
